package com.fiorano.openesb.schemarepo;

public interface SchemaErrorCodes {
    String REQUEST_HANDLER_NOT_FOUND = "REQUEST_HANDLER_NOT_FOUND";
    String ERROR_UNKNOWN_SCHEMA_REPOSITORY_SYNC_TYPE = "ERROR_UNKNOWN_SCHEMA_REPOSITORY_SYNC_TYPE";
    String IO_ERROR_SYNC_SCHEMA_REPOSITORY = "IO_ERROR_SYNC_SCHEMA_REPOSITORY";
    String IO_ERROR_SYNC_SCHEMA_REPOSITORY2 = "IO_ERROR_SYNC_SCHEMA_REPOSITORY2";
    String ERROR_SYNC_SCHEMA_REPOSITORY = "ERROR_SYNC_SCHEMA_REPOSITORY";
    String ERROR_SYNC_SCHEMA_REPOSITORY2 = "ERROR_SYNC_SCHEMA_REPOSITORY2";
    String ERROR_ADD_SCHEMA = "ERROR_ADD_SCHEMA";
    String ERROR_REMOVE_SCHEMA = "ERROR_REMOVE_SCHEMA";
    String INVALID_CONFIGURATION = "INVALID_CONFIGURATION";
    String FAIL_FETCH_SCHEMA_REPO_HANDLER_INSTANCE = "FAIL_FETCH_SCHEMA_REPO_HANDLER_INSTANCE";
    String ERROR_ADDING_SCHEMA = "ERROR_ADDING_SCHEMA";
    String FAIL_FETCH_SCHEMA = "FAIL_FETCH_SCHEMA";
    String FAIL_FETCH_LIST_ALL_SCHEMA_REFERENCES = "FAIL_FETCH_LIST_ALL_SCHEMA_REFERENCES";
}

