package com.fiorano.openesb.route;

public enum RouteOperationType {
    MESSAGE_CREATE,
    SRC_CARRY_FORWARD_CONTEXT,
    APP_CONTEXT_TRANSFORM,
    SENDER_SELECTOR,
    APP_CONTEXT_XML_SELECTOR,
    BODY_XML_SELECTOR,
    ROUTE_TRANSFORM,
    TGT_CARRY_FORWARD_CONTEXT,
    SEND;
}
